name: Acquire activation file
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Unity version to activate'
        default: '2020.1.6f1'
jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
    # Request manual activation file
    - name: Request manual activation file
      id: getManualLicenseFile
      uses: webbertakken/unity-request-manual-activation-file@v1.1
      with:
        unityVersion: ${{ github.event.inputs.version }}

    # Upload artifact (Unity_v20XX.X.XXXX.alf)
    - name: Expose as artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}
