name: Unity

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:${{ matrix.version }}-${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 2020.1.6f1
        target:
          - linux-il2cpp
    steps:
      - name: Update git
        run: |
          apt-get -y install software-properties-common
          add-apt-repository ppa:git-core/ppa
          apt-get -y update
          apt-get -y upgrade
          apt-get -y install git

      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.target }}
          restore-keys: |
            Library-

      - name: Build
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: /opt/Unity/Editor/Unity
          -projectPath "$PWD"
          -quit
          -batchmode
          -buildTarget StandaloneLinux64
          -customBuildTarget StandaloneLinux64
          -customBuildName game
          -customBuildPath "$PWD/build"
          -executeMethod BuildCommand.PerformBuild

      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
