name: Unity

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:${{ matrix.version }}-${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 2020.1.6f1
        target:
          - linux-il2cpp
    steps:
      - name: Update git and xvfb
        run: |
          apt-get -y update
          apt-get -y install software-properties-common
          add-apt-repository ppa:git-core/ppa
          apt-get -y update
          apt-get -y upgrade
          apt-get -y install git xvfb curl

      - uses: actions/checkout@v2

      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.target }}
          restore-keys: |
            Library-

      - name: License
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: echo "$UNITY_LICENSE" | tr -d '\r' > license.ulf

      - name: Activation
        run: xvfb-run --auto-servernum --server-args="-screen 0 640x480x24"
          /opt/Unity/Editor/Unity
          -batchmode
          -nographics
          -logFile /dev/stderr
          -quit
          -manualLicenseFile license.ulf
          || true

      - name: Build dir
        run: mkdir -p build

      - name: Build
        working-directory: build
        run: xvfb-run --auto-servernum --server-args="-screen 0 640x480x24"
          /opt/Unity/Editor/Unity
          -batchmode
          -nographics
          -quit
          -buildTarget Linux64
          -projectPath "../"
          -buildLinux64Player "game"
          -logFile /dev/stderr

      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
